name: appflutter_01
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/pacifico-UTN.png
  
  # Configuración de localización CORRECTAMENTE INDENTADA
l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-localization-file: l10n.dart
  output-dir: lib/generated
  output-class: S
  synthetic-package: false
  supported-locales:
    - en
    - es